// GET /api/dabia/fraud
// Returns fraud detection state. All flags are generated by deterministic rules
// tied to GOVERNANCE constants. No heuristic black boxes.

import { NextResponse } from "next/server"
import { GOVERNANCE } from "@/lib/dabia/governance"
import { FRAUD_FLAGS, TRANSACTIONS, PRODUCTS } from "@/lib/dabia/store"
import type { FraudResponse } from "@/lib/dabia/types"

// ─── Run live fraud checks against current data ──────────────────────────────

function detectVelocityViolations(): number {
  // Group transactions by buyer IP proxy (buyer ID) within 1 hour
  const windowMs = 3600 * 1000
  const now = Date.now()
  const counts: Record<string, number> = {}
  for (const tx of TRANSACTIONS) {
    if (now - new Date(tx.timestamp).getTime() < windowMs) {
      counts[tx.buyer] = (counts[tx.buyer] ?? 0) + 1
    }
  }
  return Object.values(counts).filter(c => c > GOVERNANCE.FRAUD_VELOCITY_MAX).length
}

function detectUnlinkedReviews(): number {
  // Count reviews that have no matching confirmed transaction
  const confirmedTxIds = new Set(
    TRANSACTIONS.filter(tx => tx.status === "confirmed").map(tx => tx.txId)
  )
  return PRODUCTS.flatMap(p => p.reviews).filter(r => {
    if (!GOVERNANCE.REVIEW_REQUIRES_PURCHASE) return false
    return !r.verified || !confirmedTxIds.has(r.purchaseTxId)
  }).length
}

function detectPriceInflation(): number {
  // Count products with price delta above governance threshold
  return PRODUCTS.filter(p => {
    if (!p.originalPrice) return false
    const delta = ((p.price - p.originalPrice) / p.originalPrice) * 100
    return Math.abs(delta) > GOVERNANCE.PRICE_INFLATION_FLAG_PCT
  }).length
}

export async function GET() {
  const velocityBlocked   = detectVelocityViolations()
  const reviewsRejected   = detectUnlinkedReviews()
  const inflationFlags    = detectPriceInflation()

  // Merge live detections with stored historical flags
  const allFlags = [...FRAUD_FLAGS]

  if (inflationFlags > 0 && !allFlags.find(f => f.type === "price_inflation" && !f.resolved)) {
    allFlags.push({
      type: "price_inflation", severity: "low",
      description: `${inflationFlags} listing(s) exceed ${GOVERNANCE.PRICE_INFLATION_FLAG_PCT}% price delta threshold`,
      detectedAt: new Date().toISOString(), resolved: false,
    })
  }

  const response: FraudResponse = {
    flags:            allFlags,
    openCount:        allFlags.filter(f => !f.resolved).length,
    resolvedCount:    allFlags.filter(f => f.resolved).length,
    velocityBlocked,
    reviewsRejected,
  }

  return NextResponse.json(response, {
    headers: {
      "Cache-Control":                  "no-store",
      "X-Governance-Velocity-Max":      String(GOVERNANCE.FRAUD_VELOCITY_MAX),
      "X-Governance-Review-Linked":     "true",
      "X-Governance-Inflation-Flag":    String(GOVERNANCE.PRICE_INFLATION_FLAG_PCT),
    },
  })
}
